yarnPath: .yarn/releases/yarn-3.3.1.cjs

# Download swc (and so on) packages for all architectures and OSes, so that other contributors to this repo get them out of the box.
supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - current
    - x64
