name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - name: Get Node.js version
        run: echo "NODE_VERSION=$(jq -r .volta.node package.json)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: pnpm run check

      - run: pnpm run jest
